# Generated by Django 5.2 on 2025-05-20 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MiniAppCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="minis/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AWS", "AMAZON WEB SERVICE"),
                            ("GCP", "GOOGLE CLOUD PLATFORM"),
                            ("MSA", "MICROSOFT AZURE"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
