# Generated by Django 5.2 on 2025-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="miniappcategory",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
