# Generated by Django 5.2 on 2025-05-25 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minapp", "0003_miniappreview_organization_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="minapp.organization",
            ),
        ),
    ]
